# -*- mode: ruby -*-
# vi: set ft=ruby :

if File.exist?('.env.local')
  File.readlines('.env.local').each do |line|
    line = line.strip
    next if line.empty? || line.start_with?('#') # Skip comments

    key, value = line.split('=', 2)
    ENV[key] = value if key && value
  end
else
  puts "Warning: env.local file not found!"
  exit(1)
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_version = "4.3.12"

  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.hostname = "xvoorvaaS"
  config.vm.provision "shell", path: "script.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "xvoorvaaS"
    vb.memory = "1024"
    vb.cpus = "1"
  end
end
