Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"
  
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.hostname = "vpacS"

  config.vm.provision "shell", path:"deploy.sh"

  config.vm.provider "virtualbox" do |v|
    v.name = "vpacS"
    v.memory = "2048"
    v.cpus = "2"

  end
end
