# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_version = "4.3.12"

  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provision "shell", path: "script.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end
end
