apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocluster
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: confs
    repoURL: https://github.com/42xannyx/inception-of-things.git
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
